import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const {
    data: session,
    isLoading,
    error,
  } = trpc.useQuery(["session.get-session"]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        {session ? (
          <>
            <Link href="/play">Start quizzin'</Link>
          </>
        ) : (
          <>
            <Link href="/api/auth/signin">Log in!</Link>
          </>
        )}
      </main>
    </>
  );
};

export default Home;
